name: tcn
batch_size: 50

init:
  _target_: src.models.tcn.TCN_NILM
  input_window_length: 600
  depth: 9
  nb_filters: [512, 256, 256, 128, 128, 256, 256, 256, 512]
  res_l2: 0
  stacks: 1
  dropout: 0.2
